models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $last_name
 * @property string $first_name
 * @property string $username
 * @property string $password
 * @property string $auth_key
 * @property string $access_token
 */
class User extends \yii\db\ActiveRecord
{

    public $user_role;
    public $item_name;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['last_name', 'first_name', 'middle_name', 'username', 'password', 'user_role'], 'required'],
            [['last_name', 'first_name', 'middle_name', 'username'], 'string', 'max' => 50],
            [['password', 'auth_key', 'access_token'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['authAssignment.item_name'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'last_name' => Yii::t('user', 'Last Name'),
            'first_name' =>  Yii::t('user', 'First Name'),
            'middle_name' =>  Yii::t('user', 'Middle Name'),
            'username' =>  Yii::t('user', 'Login'),
            'password' =>  Yii::t('user', 'Password'),
            'auth_key' =>  Yii::t('user', 'Auth Key'),
            'access_token' =>  Yii::t('user', 'Access Token'),
            'user_role' =>  Yii::t('user', 'User Permission'),
            'fullName' =>  Yii::t('user', 'Full Name'),
        ];
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserIdentity;
use app\models\UserSearch;
use app\models\PatientCard;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use app\models\AuthAssignment;
use app\models\MedicalCardForm;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (\Yii::$app->user->can('ViewUser')) {
            $searchModel = new UserSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (\Yii::$app->user->can('viewUser')) {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(\Yii::$app->user->can('createUser')) {
            $model = new UserIdentity();

            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                
                $model->password = md5($model->password);
                
                $model->save(false);

                $auth = Yii::$app->authManager;
                $userRole = $auth->getRole($model->user_role);
                $auth->assign($userRole, $model->getId());

                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new HttpException(403 ,'Forbidden');
            
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->can('updateUser')) {
            $model = $this->findModel($id);

            $old_password = $model->password;

            $roles = $model->authAssignment;

            if ($model->load(Yii::$app->request->post()) && $roles->load(Yii::$app->request->post()) && $model->validate()) {

                if ($old_password != $model->password) {
                    $model->password = md5($model->password);
                }

                $model->save(false);
                $roles->save(false);
                    
                PatientCard::updatePatientFromUser($model);

                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'roles' => $roles,
                ]);
            } 
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->can('deleteUser'))  {

            if ($auth_asssignment = AuthAssignment::find()->where(['user_id' => $id])->one()) {
                $auth_asssignment->delete();
            }

            if ($patient_card = PatientCard::find()->where(['user_id' => $id])->one()) {

                if ($medical_card_form = MedicalCardForm::find()->where(['patient_card_id' => $patient_card->patient_id])->all()) {
                    foreach ($medical_card_form as $med_form) {
                        $med_form->delete();
                    }
                }

                $patient_card->delete();
            }

            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserIdentity::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'access_token') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('user', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('user', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\AuthItem;
use app\components\Common;
/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('user', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    
	<div class="user-form">

	    <?php $form = ActiveForm::begin(); ?>

	    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'middle_name')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

	    <?php 
	    	$roles = Yii::$app->authManager->getRoles(); 
	    	if (isset($roles['basic'])) {
		     	unset($roles['basic']);
		     }
	     ?>
	    <?= $form->field($model, 'user_role')->dropDownList(Common::transarray(ArrayHelper::map($roles, 'name', 'description')),['prompt' => Yii::t('user','Choose user role')]); ?>

	    <div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Create') : Yii::t('user', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>

	    <?php ActiveForm::end(); ?>

	</div>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\authAssignment;
use app\components\Common;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('user', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php 
            if(\Yii::$app->user->can('createUser')) { 
               echo Html::a(Yii::t('user', 'Create User'), ['create'], ['class' => 'btn btn-success']); 
            } 
        ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'fullName',
            'username',
             [
                'attribute' => 'role',
                'label'     => Yii::t('user','Role'),
                //'value' => 'authItem.description',
                'value' => function($model) {
                   return Yii::t('common',$model->authItem->description);
                },
                'filter' =>Html::activeDropDownList(
                    $searchModel, 
                    'authAssignment.item_name',
                    Common::transarray(ArrayHelper::map(Yii::$app->authManager->getRoles(), 'name', 'description')),
                    ['class' => 'form-control', 'prompt' => Yii::t('user', 'Select role')]
                ),

            ],
            [
               'class' => \yii\grid\ActionColumn::className(),
               'buttons'=>[
                    'view'=>function ($url, $model) {
                        if(\Yii::$app->user->can('viewUser')) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['user/view','id'=>$model['id']]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $customurl, ['title' => Yii::t('yii', 'View'), 'data-pjax' => '0']);
                        }
                    },
                    'update' => function ($url, $model) {
                        if(\Yii::$app->user->can('updateUser')) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['user/update','id'=>$model['id']]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-pencil"></span>', $customurl, ['title' => Yii::t('yii', 'Update'), 'data-pjax' => '0']);
                        }
                    },
                    'delete' => function ($url, $model) {
                        if(\Yii::$app->user->can('deleteUser')) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['user/delete','id'=>$model['id']]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-trash"></span>', $customurl, ['title' => Yii::t('yii', 'Delete'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },
                ],
               'template'=>'{view} {update} {delete}',
           ],
        ],
    ]); ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\AuthItem;
use app\components\Common;
/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('user', 'Update user:	') . $model->last_name . ' ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->last_name . ' ' . $model->first_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('user', 'Update');

$user_roles = Yii::$app->authManager->getRoles(); 
$current_user_role = Yii::$app->authManager->getRolesByUser($model->id);
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    
	<div class="user-form">

	    <?php $form = ActiveForm::begin(); ?>
	    <?php if (!isset($current_user_role['basic'])) {?>
		    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

		    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

	    	<?= $form->field($model, 'middle_name')->textInput(['maxlength' => true]) ?>
	    <?php } else {?>
		    <?= $form->field($model, 'last_name')->textInput(['disabled' => true]) ?>

		    <?= $form->field($model, 'first_name')->textInput(['disabled' => true]) ?>

	    	<?= $form->field($model, 'middle_name')->textInput(['disabled' => true]) ?>
	    <?php }?>
	    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

	    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

	    <?php 
		    if (!isset($current_user_role['basic'])) {
		    	if (isset($user_roles['basic'])) {
			     	unset($user_roles['basic']);
			    }
	    ?>
	    	<?= $form->field($roles, 'item_name')->dropDownList(Common::transarray(ArrayHelper::map($user_roles, 'name', 'description')),['prompt' => Yii::t('user', 'Choose user role')]); ?>
	    <?php } else {?>
	    	<?= $form->field($roles, 'item_name')->dropDownList(Common::transarray(ArrayHelper::map($user_roles, 'name', 'description')),['style' => 'display: none','prompt' => Yii::t('user', 'Choose user role')]); ?>
	    <?php }?>

	    <div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Create') : Yii::t('user', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>

	    <?php ActiveForm::end(); ?>

	</div>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('user', 'User') . ': ' . $model->last_name . ' ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('user', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('user', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('user', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'fullName',
            'username',
            //'authItem.description',
            [
                'attribute' => 'role',
                'label'     => Yii::t('user','Role'),
                'value' => function ($model) {
                    return Yii::t('common', $model->authItem->description);
                },
            ],
            //'password',
            //'auth_key',
            //'access_token',
        ],
    ]) ?>

</div>
    