controllers/MedicalCardFormController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MedicalCardForm;
use app\models\MedicalCardFormSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;

use app\models\PatientCard;
use app\components\Common;
use app\models\Epikriz;
use app\models\Diary;
use app\models\ReceiveDoctorNote;
use app\models\Surgeries;
use app\models\WorkIncapacityLists;
use app\models\Anatomopathological;



use kartik\mpdf\Pdf;
/**
 * MedicalCardFormController implements the CRUD actions for MedicalCardForm model.
 */
class MedicalCardFormController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MedicalCardForm models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId(Yii::$app->request->get('id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {

            $searchModel = new MedicalCardFormSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->renderPartial('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            return $this->renderPartial('acccess_denied');
        }
    }

    /**
     * Displays a single MedicalCardForm model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $patient_id)
    {
        if (Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId($patient_id)== Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {

            $model = $this->findModel($id);

            if($model->hospitalisation_datetime != NULL && $model->closed_datetime == NULL) {
                $model->bed_days = round(floor(strtotime(date('Y-m-d H:i:s')) - strtotime($model->hospitalisation_datetime)) / (60 * 60 * 24),2);
            } elseif($model->hospitalisation_datetime != NULL && $model->closed_datetime != NULL) {
                $model->bed_days = round(floor(strtotime($model->closed_datetime) - strtotime($model->hospitalisation_datetime)) / (60 * 60 * 24),2);
            } else {
                $model->bed_days = NULL;
            }

            if ($model->hospitalisation_variants_id == 1) {
                $model->hospitalisation_variants_id = Yii::t('patient_medical_form', 'Urgent indications');
            } elseif($model->hospitalisation_variants_id == 2) {
                $model->hospitalisation_variants_id = $model->hospitalisation_time .  Yii::t('patient_medical_form', ' hours after onset of the disease, an injury; routinely');
            } else {
                $model->hospitalisation_variants_id = NULL;
            }
        

            $model->blood_type_id = Common::transelement(MedicalCardForm::getBloodTypeById($model->blood_type_id));
            $model->rhesus_affilation = Common::transelement(MedicalCardForm::getRhesusAffilationById($model->rhesus_affilation));

            return $this->render('view', [
                'model' => $model,
                'patient' => PatientCard::findOne($patient_id),
                'surgeries' => Yii::$app->runAction('surgeries/index'),
                'receive_doctor_note' => Yii::$app->runAction('receive-doctor-note/index'),
                'work_incapacity_lists' => Yii::$app->runAction('work-incapacity-lists/index'),
                'diary' => Yii::$app->runAction('diary/index'),
                'epikriz' => $this->findEpikriz($id),
                'anatomopathological' => $this->findAnatomopathological($id),
            ]);
        } else {
            throw new HttpException(403, 'Forbidden');
        }
    }

    /**
     * Creates a new MedicalCardForm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($patient_id = null)
    {
        if ($patient_id) {
            if (Yii::$app->user->can('createPost')) {
                $model = new MedicalCardForm();

                $model->patient_card_id = $patient_id;
                
                if ($model->load(Yii::$app->request->post())) {
                    if ($model->move_to_department_id != NULL) {
                        $model->closed_datetime = date('Y-m-d H:i:s');
                    }
                    if ($model->diagnosis_clinical != NULL && $model->diagnosis_clinical != '') {
                        $model->diagnosis_clinical_date = date('Y-m-d H:i:s');
                    }
                }
                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id]);
                } else {
                    return $this->render('create', [
                        'model' => $model,
                        'patient' => PatientCard::findOne($patient_id),
                    ]);
                }
            } else {
                throw new HttpException(403, 'Forbidden');
            }
        }  else {
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    /**
     * Updates an existing MedicalCardForm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id,$patient_id = null)
    {
        if ($patient_id) {
            if(Yii::$app->user->can('updatePost')) {
                $model = $this->findModel($id);

                $model->patient_card_id = $patient_id;

                if ($model->load(Yii::$app->request->post())) {
                    if ($model->move_to_department_id != NULL) {
                        $model->closed_datetime = date('Y-m-d H:i:s');
                    }
                }

                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id]);
                } else {
                    return $this->render('update', [
                        'model' => $model,
                        'patient' => PatientCard::findOne($patient_id), 
                    ]);
                }
            } else {
                throw new HttpException(403, 'Forbidden');
            }
        }  else {
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    /**
     * Deletes an existing MedicalCardForm model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id, $patient_id)
    {
        if(Yii::$app->user->can('deletePost')) {
            
            //Епикриз
            if ($epikriz = Epikriz::find()->where(['medical_card_id' => $id])->one()) {            
                $epikriz->delete();
            }

            //Записи в дневнике
            if ($diary = Diary::find()->where(['medical_card_form_id' => $id])->all()) {
                foreach ($diary as $diar) {
                    $diar->delete();
                }
            }

            //Хирург операции
            if ($surgeries = Surgeries::find()->where(['medical_card_form_id' => $id])->all()) {
                foreach ($surgeries as $surgery) {
                    $surgery->delete();
                }
            }

            //Листки непрацездатності
            if ($work_incapacity_lists = WorkIncapacityLists::find()->where(['medical_card_form_id' => $id])->all()) {
                foreach ($work_incapacity_lists as $work_incapacity_list) {
                    $work_incapacity_list->delete();
                }
            }

            //Записи врача приемного
            if ($receive_doctor_notes = ReceiveDoctorNote::find()->where(['medical_card_form_id' => $id])->all()) {
                foreach ($receive_doctor_notes as $receive_doctor_note) {
                    $receive_doctor_note->delete();
                }
            }

            //Мед. форма
            $this->findModel($id)->delete();
            return $this->redirect(['patient-card/view', 'id' => $patient_id]);
        } else {
            throw new HttpException(403, 'Forbidden');
        }
    }

    public function actionOpenCard($id, $patient_id)
    {
        if(Yii::$app->user->can('updatePost')) {
            Yii::$app->db->createCommand()
                    ->update('medical_card_form', ['closed_datetime' => NULL], 'id = "' . $id . '"')
                    ->execute();

            return $this->redirect(['patient-card/view', 'id' => $patient_id]);           
        } else {
            throw new HttpException(403, 'Forbidden');
        }
    }

    public function actionCloseCard($id, $patient_id)
    {
        if(Yii::$app->user->can('updatePost')) {
            Yii::$app->db->createCommand()
                    ->update('medical_card_form', ['closed_datetime' => date('Y-m-d H:i:s')], 'id = "' . $id . '"')
                    ->execute();

            return $this->redirect(['patient-card/view', 'id' => $patient_id]);           
        } else {
            throw new HttpException(403, 'Forbidden');
        }
    }

    public function actionPdf($id, $patient_id) {
        if(Yii::$app->user->can('viewPost')) {
            $pdf = Yii::$app->pdf;
            
            $model = $this->findModel($id);

            if($model->hospitalisation_datetime != NULL && $model->closed_datetime == NULL) {

views/medical-card-form/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

use app\models\Departments;
use app\models\Lang;
use app\models\UserIdentity;
use app\models\ClassMkb;
use app\models\Workabilities;
use app\models\Outcomes;
use app\models\ServiceMalignantFormations;

use yii\bootstrap\Tabs;
use app\components\Common;
/* @var $this yii\web\View */
/* @var $model app\models\MedicalCardForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="medical-card-form-form">

    <?php $form = ActiveForm::begin(); ?>

    <!--<?= $form->field($model, 'returns_time')->textInput() ?>-->

    <?= $model->isNewRecord ?$form->field($model, 'hospitalisation_datetime')->textInput(['value' => date('Y-m-d H:i:s'), 'readonly' => true]) : $form->field($model, 'hospitalisation_datetime')->textInput(['readonly' => true]) ?>
    <?php
        echo Tabs::widget([
            'items' => [
                [  
                    'label' => Yii::t('patient_medical_form', 'General info'),
                    'content' => 
                                $form->field($model, 'medical_card_number')->textInput(['maxlength' => true]) .

                                $form->field($model, 'department_id')->dropDownList(Common::transarray(ArrayHelper::map(Departments::find()->all(), 'dept_id', 'dept_name')),['prompt' => Yii::t('patient_medical_form','Select department')]) .

                                $form->field($model, 'chamber')->textInput(['maxlength' => true, 'placeholder' => Yii::t('patient_medical_form', 'Input chamber')]) .
                                
                                

                                $form->field($model, 'move_to_department_id')->dropDownList(Common::transarray(ArrayHelper::map(Departments::find()->all(), 'dept_id', 'dept_name')),['prompt' => Yii::t('patient_medical_form','Select department')]) .

                                $form->field($model, 'blood_type_id')->dropDownList(Common::transarray([
                                    '1' =>  Yii::t('patient_medical_form','0 (I) - first type'),
                                    '2' =>  Yii::t('patient_medical_form','A (II) - second type'),
                                    '3' =>  Yii::t('patient_medical_form','B (III) - third type'),
                                    '4' =>  Yii::t('patient_medical_form','AB (IV) - fourth type'),
                                ]),['prompt' => Yii::t('patient_medical_form', 'Choose Blood Type')]) .

                                $form->field($model, 'rhesus_affilation')->dropDownList(Common::transarray([
                                    '0' =>  Yii::t('patient_medical_form','Rh(-) - negative'),
                                    '1' =>  Yii::t('patient_medical_form','Rh(+) - positive'),

                                ]),['prompt' => Yii::t('patient_medical_form', 'Choose Rhesus')]) .

                                $form->field($model, 'rw_examination')->widget(\yii\jui\DatePicker::classname(), [
                                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                                    'dateFormat' => 'yyyy-MM-dd',
                                    'clientOptions' => [
                                        'changeMonth' => true,
                                        'yearRange' => '1991:2099',
                                        'changeYear' => true,
                                    ],
                                    'options' => ['class' => 'form-control', 'placeholder' => Yii::t('patient_medical_form', 'Select RW Date')],
                                ]) .

                                $form->field($model, 'vil_examination')->widget(\yii\jui\DatePicker::classname(), [
                                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                                    'dateFormat' => 'yyyy-MM-dd',
                                    'clientOptions' => [
                                        'changeMonth' => true,
                                        'yearRange' => '1991:2099',
                                        'changeYear' => true,
                                    ],
                                    'options' => ['class' => 'form-control', 'placeholder' => Yii::t('patient_medical_form', 'Select Vil Date')],
                                ]) .
                                $form->field($model, 'side_effects')->textarea(['rows' => 3]) .
                                $form->field($model, 'sent_by_clinic')->textInput(['maxlength' => true]) .

                                '<div class="form-group field-medicalcardform-hospitalisation_variants_id">
                                    <label class="control-label">' . Yii::t('patient_medical_form', 'Hospitalisation Variants') .'</label>
                                    <input type="hidden" name="MedicalCardForm[hospitalisation_variants_id]" value=""><div id="medicalcardform-hospitalisation_variants_id" class="form-checkboxes"><label><input type="radio" name="MedicalCardForm[hospitalisation_variants_id]" value="1">' . Yii::t('patient_medical_form', 'Urgent indications') .'</label>
                                    <label><input type="radio" name="MedicalCardForm[hospitalisation_variants_id]" value="2">&nbsp;<input type="text" id="medicalcardform-hospitalisation_time" class="checkbox_input" name="MedicalCardForm[hospitalisation_time]" maxlength="10">' . Yii::t('patient_medical_form', ' hours after onset of the disease, an injury; routinely') .'  </label></div>

                                    <div class="help-block"></div>
                                </div>'
                    ,
                    'active' => true // указывает на активность вкладки
                ],
                [
                    'label' => Yii::t('patient_medical_form','Diagnoses'),
                    'content' => 

                                $form->field($model, 'diagnosis_default')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                                $form->field($model, 'diagnosis_hospitalisation')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                                $form->field($model, 'diagnosis_clinical')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                               /* $form->field($model, 'diagnosis_clinical_date')->widget(\yii\jui\DatePicker::classname(), [
                                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                                    'dateFormat' => 'yyyy-MM-dd',
                                    'clientOptions' => [
                                        'changeMonth' => true,
                                        'yearRange' => '1991:2099',
                                        'changeYear' => true,
                                    ],
                                    'options' => ['class' => 'form-control', 'placeholder' => Yii::t('patient_medical_form', 'Select Diagnosis Clinical Date')],
                                ]) .*/

                                $form->field($model, 'diagnosis_clinical_doctor')->dropDownList(ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),['prompt' => Yii::t('patient_medical_form','Select doctor')]) .

                                $form->field($model, 'diagnosis_final')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                                $form->field($model, 'diagnosis_final_main')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                                $form->field($model, 'diagnosis_final_main_complication')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) .

                                $form->field($model, 'diagnosis_final_concomitant')->widget(\yii\jui\AutoComplete::classname(), [
                                    'options' => ['class' => 'form-control'],
                                    'clientOptions' => [
                                        'source' => ClassMkb::getDiagnoses(),
                                    ],
                                ]) 
                                ,
                ],
                [
                    'label' => Yii::t('patient_medical_form', 'Conclusion'),
                    'content' => 
                                $form->field($model, 'other_medical_services')->textarea(['rows' => 6]) .

                                $form->field($model, 'other_medical_services_malignant_formation_id')->radioList(Common::transarray(ArrayHelper::map(ServiceMalignantFormations::getValues(), 'id', 'value')),['class' => 'form-checkboxes']) .

                                $form->field($model, 'workability_id')->radioList(Common::transarray(ArrayHelper::map(Workabilities::getWorkabilities(), 'id', 'value')),['class' => 'form-checkboxes']) .

                                $form->field($model, 'conclusion_expertise')->textarea(['rows' => 6]) .

                                $form->field($model, 'outcome_id')->radioList(Common::transarray(ArrayHelper::map(Outcomes::getOutcomes(), 'id', 'value')),['class' => 'form-checkboxes']) .

                                $form->field($model, 'notes')->textarea(['rows' => 6]) 
                                ,
                ],
            ]
        ]);
    ?>
.

    <?= $form->field($model, 'doctor')->dropDownList(ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),['prompt' => Yii::t('patient_medical_form','Select doctor')]) ?>

    <?= $form->field($model, 'department_head')->dropDownList(ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),['prompt' => Yii::t('patient_medical_form','Select doctor')]) ?>
    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('yii', 'Create') : Yii::t('yii', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/medical-card-form/acccess_denied.php
<?= 'access denied';?>

views/medical-card-form/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\MedicalCardForm */

$this->title = Yii::t('patient_medical_form', 'Create Medical Card Form');
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', 'Patient Cards'), 'url' => ['patient-card/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="medical-card-form-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'patient' => $patient,
    ]) ?>

</div>

views/medical-card-form/index.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use yii\widgets\Pjax;

use dosamigos\datetimepicker\DateTimePicker;

use app\models\Lang;
use app\models\Departments;
use app\models\UserIdentity;
use app\models\PatientCard;
use app\components\Common;
/* @var $this yii\web\View */
/* @var $searchModel app\models\MedicalCardFormSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="medical-card-form-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php 
            if(\Yii::$app->user->can('createPatient')) { 
               echo Html::a(
                    Yii::t('patient_medical_form', 'Create Medical Card Form'),
                    ['create', 'patient_id' => Yii::$app->request->get('id')], 
                    ['class' => 'btn btn-success']
                ); 
            } 
        ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'medical_card_number',
            [
                'attribute' => 'hospitalisation_datetime',
                'value'     => 'hospitalisation_datetime',
                'format' => 'raw',
                'options' => ['class'=>'several-datepicker-filters'],
                'filter' => DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'hospitalisation_datetime_from',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd HH:ii:ss',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'From'), 'class' => 'form-control datepicker-filter'],
                ]) . ' ' . DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'hospitalisation_datetime_to',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd HH:ii:ss',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'To'), 'class' => 'form-control datepicker-filter'],
                ]) ,

            ],
            [
                'label' => Yii::t('patient_card', 'Departments Dept Name'),
                'attribute' => 'departments.dept_name',
                'value' => function($model) {
                    return Common::transelement($model->departments->dept_name);
                },
                'format' => 'html',
                'filter' => Html::activeDropDownList(
                    $searchModel, 
                    'departments.dept_id',
                    Common::transarray(ArrayHelper::map(Departments::getDepartments(), 'dept_id', 'dept_name')),
                    ['class' => 'form-control', 'prompt' => Yii::t('patient_medical_form', 'Select department')]
                ),
            ],
            [
                'label' => Yii::t('patient_card', 'Doctor Full Name'),
                'attribute' => 'doctor_full_name',
                'value' => function ($model) {
                    return $model->user->getFullName();
                },
                'filter' =>Html::activeDropDownList(
                    $searchModel, 
                    'user.id',
                    ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),
                    ['class' => 'form-control', 'prompt' => Yii::t('patient_medical_form', 'Select doctor')]
                ),
            ],
            [
               'class' => \yii\grid\ActionColumn::className(),
               'buttons'=>[
                    'view'=>function ($url, $model) {
                        if(\Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId(Yii::$app->request->get('id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/view','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $customurl, ['title' => Yii::t('yii', 'View'), 'data-pjax' => '0']);
                        }
                    },
                    'update' => function ($url, $model) {
                        if(\Yii::$app->user->can('updatePost') && $model['closed_datetime'] == NULL) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/update','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-pencil"></span>', $customurl, ['title' => Yii::t('yii', 'Update'), 'data-pjax' => '0']);
                        }
                    },
                    'delete' => function ($url, $model) {
                        if(\Yii::$app->user->can('deletePost') && $model['closed_datetime'] == NULL     && isset(\Yii::$app->authManager->getRolesByUser(Yii::$app->user->identity->id)['admin'])) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/delete','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-trash"></span>', $customurl, ['title' => Yii::t('yii', 'Delete'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },
                    'open_card' => function ($url, $model) {
                        if(\Yii::$app->user->can('createUser') && $model['closed_datetime'] != NULL  && isset(\Yii::$app->authManager->getRolesByUser(Yii::$app->user->identity->id)['admin'])) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/open-card','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-open"></span>', $customurl, ['title' => Yii::t('common', 'Open Card'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },

                    /*'create_pdf' => function ($url, $model) {
                        if(\Yii::$app->user->can('viewPost')) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/pdf','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-print"></span>', $customurl, ['title' => Yii::t('common', 'Create PDF'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },*/
                    'close_card' => function ($url, $model) {
                        if(\Yii::$app->user->can('createUser') && $model['closed_datetime'] == NULL && isset(\Yii::$app->authManager->getRolesByUser(Yii::$app->user->identity->id)['admin'])) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['medical-card-form/close-card','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-save"></span>', $customurl, ['title' => Yii::t('yii', 'Close Card'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    }
                ],
               'template'=>'{view} {update} {delete} {open_card} {close_card}',
           ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/medical-card-form/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MedicalCardForm */

$this->title = Yii::t('patient_medical_form', 'Update Medical Card Form: ') . $model->medical_card_number;
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', 'Patient Cards'), 'url' => ['patient-card/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = Yii::t('yii', 'Update');
?>
<div class="medical-card-form-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'patient' => $patient,
    ]) ?>

</div>