models/Diary.php
<?php

namespace app\models;

use Yii;
use app\models\UserIdentity;
use app\models\MedicalCardForm;
/**
 * This is the model class for table "diary".
 *
 * @property integer $id
 * @property integer $medical_card_form_id
 * @property string $datetime_added
 * @property string $pulse
 * @property string $arterial_pressure
 * @property string $temprature
 * @property string $breathing
 * @property string $weight
 * @property string $drink_quantity
 * @property string $daily_pee
 * @property string $emptying
 * @property string $bath
 * @property string $comments
 * @property integer $doctor_id
 */
class Diary extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'diary';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['medical_card_form_id', 'doctor_id', 'pulse'], 'integer'],
            [['datetime_added'], 'safe'],
            [['comments'], 'string'],
            [['pulse', 'arterial_pressure', 'temprature', 'breathing', 'weight', 'drink_quantity', 'daily_pee', 'emptying', 'bath'], 'string', 'max' => 50],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('diary', 'ID'),
            'medical_card_form_id' => Yii::t('diary', 'Medical Card Form ID'),
            'datetime_added' => Yii::t('diary', 'Datetime Added'),
            'pulse' => Yii::t('diary', 'Pulse'),
            'arterial_pressure' => Yii::t('diary', 'Arterial Pressure'),
            'temprature' => Yii::t('diary', 'Temprature'),
            'breathing' => Yii::t('diary', 'Breathing'),
            'weight' => Yii::t('diary', 'Weight'),
            'drink_quantity' => Yii::t('diary', 'Drink Quantity'),
            'daily_pee' => Yii::t('diary', 'Daily Pee'),
            'emptying' => Yii::t('diary', 'Emptying'),
            'bath' => Yii::t('diary', 'Bath'),
            'comments' => Yii::t('diary', 'Comments'),
            'doctor_id' => Yii::t('diary', 'Doctor ID'),
        ];
    }

    public function getMedicalCardForm()
    {
        return $this->hasOne(MedicalCardForm::className(), ['id' => 'medical_card_form_id']);
    }

    public function getUser()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }

    public function getDoctor()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }

    public function getDoctors()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }
}

controllers/DiaryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Diary;
use app\models\DiarySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use app\models\PatientCard;
use app\models\MedicalCardForm;
/**

/**
 * DiaryController implements the CRUD actions for Diary model.
 */
class DiaryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Diary models.
     * @return mixed
     */
    public function actionIndex()
    {

        if (\Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId(Yii::$app->request->get('patient_id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
            $searchModel = new DiarySearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->renderPartial('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Displays a single Surgeries model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId($patient_id) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
            return $this->render('view', [
                'model' => $this->findModel($id),
                'patient' => PatientCard::findOne($patient_id),
                'medical_data' => MedicalCardForm::findOne($medical_card_id),
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Creates a new Surgeries model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('createPost')) {
            $model = new Diary();

            $model->medical_card_form_id =  Yii::$app->request->get('medical_card_id');
            $model->doctor_id = Yii::$app->user->identity->id;
            $model->datetime_added = date('Y-m-d H:i:s');

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id, 'medical_card_id' => $medical_card_id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'patient' => PatientCard::findOne($patient_id),
                    'medical_data' => MedicalCardForm::findOne($medical_card_id),
                ]);
            }
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Updates an existing Surgeries model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('updatePost')) {
            $model = $this->findModel($id);

            $model->medical_card_form_id =  Yii::$app->request->get('medical_card_id');

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id, 'medical_card_id' => $medical_card_id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'patient' => PatientCard::findOne($patient_id),
                    'medical_data' => MedicalCardForm::findOne($medical_card_id),
                ]);
            }
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Deletes an existing Surgeries model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id,$patient_id,$medical_card_id)
    {
        if (\Yii::$app->user->can('deletePost')) {
            $this->findModel($id)->delete();

            return $this->redirect(['medical-card-form/view', 'id' => $medical_card_id, 'patient_id' => $patient_id]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Finds the Diary model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Diary the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Diary::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/diary/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Lang;
use yii\helpers\ArrayHelper;
use app\models\UserIdentity;
/* @var $this yii\web\View */
/* @var $model app\models\Diary */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="diary-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'pulse')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'arterial_pressure')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'temprature')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'breathing')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'weight')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'drink_quantity')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'daily_pee')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'emptying')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'bath')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'comments')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('yii', 'Create') : Yii::t('yii', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/diary/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DiarySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="diary-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'medical_card_form_id') ?>

    <?= $form->field($model, 'datetime_added') ?>

    <?= $form->field($model, 'pulse') ?>

    <?= $form->field($model, 'arterial_pressure') ?>

    <?php // echo $form->field($model, 'temprature') ?>

    <?php // echo $form->field($model, 'breathing') ?>

    <?php // echo $form->field($model, 'weight') ?>

    <?php // echo $form->field($model, 'drink_quantity') ?>

    <?php // echo $form->field($model, 'daily_pee') ?>

    <?php // echo $form->field($model, 'emptying') ?>

    <?php // echo $form->field($model, 'bath') ?>

    <?php // echo $form->field($model, 'comments') ?>

    <?php // echo $form->field($model, 'doctor_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('diary', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('diary', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/diary/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Diary */

$this->title = Yii::t('diary', 'Create Diary');
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="diary-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/diary/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\UserIdentity;
use yii\widgets\Pjax;
use dosamigos\datetimepicker\DateTimePicker;
use app\models\Lang;
use app\models\MedicalCardForm;
use app\models\PatientCard;
/* @var $this yii\web\View */
/* @var $searchModel app\models\DiarySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('diary', 'Diaries');
?>
<div class="diary-index">


    <p>
        <?php 
        if (\Yii::$app->user->can('createPost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) {
         echo Html::a(Yii::t('diary', 'Create Diary Note'), ['create', 'medical_card_id' => Yii::$app->request->get('id'), 'patient_id' => Yii::$app->request->get('patient_id')], ['class' => 'btn btn-success']);
        }
        ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'datetime_added',
                'value'     => 'datetime_added',
                'format' => 'raw',
                'options' => ['class'=>'several-datepicker-filters'],
                'filter' => DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'datetime_from',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd H:i:s',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'From'), 'class' => 'form-control datepicker-filter'],
                ]) . ' ' . DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'datetime_to',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd H:i:s',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'To'), 'class' => 'form-control datepicker-filter'],
                ]) ,

            ],
            [
                'attribute' => 'doctor_full_name',
                'label' => Yii::t('diary', 'doctor'),
                'value' => function ($model) {
                    if($model->user && isset(\Yii::$app->authManager->getRolesByUser($model->doctor_id)['author'])) {
                        return $model->user->getFullName();
                    } 
                },
                'filter' =>Html::activeDropDownList(
                    $searchModel, 
                    'user.id',
                    ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),
                    ['class' => 'form-control', 'prompt' => Yii::t('patient_medical_form', 'Select doctor')]
                ),
            ],

            [
               'class' => \yii\grid\ActionColumn::className(),
               'buttons'=>[
                    'view'=>function ($url, $model) {
                       if((\Yii::$app->user->can('viewPost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) || (PatientCard::getUserIdByCardId(Yii::$app->request->get('patient_id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['diary/view','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $customurl, ['title' => Yii::t('yii', 'View'), 'data-pjax' => '0']);
                        }
                    },
                    'update' => function ($url, $model) {
                        if(\Yii::$app->user->can('updatePost')  && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id')) && Yii::$app->user->identity->id == $model['doctor_id'] || isset(Yii::$app->authManager->getRolesByUser(Yii::$app->user->getId())['admin'])) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['diary/update','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-pencil"></span>', $customurl, ['title' => Yii::t('yii', 'Update'), 'data-pjax' => '0']);
                        }
                    },
                    'delete' => function ($url, $model) {
                        if(\Yii::$app->user->can('deletePost')  && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['diary/delete','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-trash"></span>', $customurl, ['title' => Yii::t('yii', 'Delete'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },
                ],
               'template'=>'{view} {update} {delete}',
           ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/diary/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Diary */

$this->title = Yii::t('diary', 'Update Diary') . $model->datetime_added;
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = Yii::t('diary', 'Update');
?>
<div class="diary-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/diary/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\UserIdentity;
/* @var $this yii\web\View */
/* @var $model app\models\Diary */

$this->title = Yii::t('diary', 'Diary Note: ').$model->datetime_added;
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="diary-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'datetime_added',
            'pulse',
            'arterial_pressure',
            'temprature',
            'breathing',
            'weight',
            'drink_quantity',
            'daily_pee',
            'emptying',
            'bath',
            'comments:ntext',
            [
                'label' => Yii::t('surgeries','Doctor'),
                'value' => UserIdentity::getDoctorById($model->doctor_id),
            ],
        ],
    ]) ?>

</div>