models/ReceiveDoctorNote.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "receive_doctor_note".
 *
 * @property integer $id
 * @property integer $medical_card_form_id
 * @property string $complaints
 * @property string $disease_anamnesis
 * @property string $life_anamnesis
 * @property string $patient_objective_condition
 * @property string $datetime_added
 */
class ReceiveDoctorNote extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'receive_doctor_note';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['medical_card_form_id'], 'integer'],
            [['complaints', 'disease_anamnesis', 'life_anamnesis', 'patient_objective_condition'], 'string'],
            [['datetime_added', 'doctor_id'], 'safe'],
        ];
    }



    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('receive_doctor_note', 'ID'),
            'medical_card_form_id' => Yii::t('patient_medical_from', 'Medical Card Form №'),
            'doctor_id' => Yii::t('patient_medical_form', 'Doctor'),
            'complaints' => Yii::t('receive_doctor_note', 'Complaints'),
            'disease_anamnesis' => Yii::t('receive_doctor_note', 'Disease Anamnesis'),
            'life_anamnesis' => Yii::t('receive_doctor_note', 'Life Anamnesis'),
            'patient_objective_condition' => Yii::t('receive_doctor_note', 'Patient Objective Condition'),
            'datetime_added' => Yii::t('receive_doctor_note', 'Datetime Added'),
        ];
    }

    public function getMedicalCardForm()
    {
        return $this->hasOne(MedicalCardForm::className(), ['id' => 'medical_card_form_id']);
    }

    public function getUser()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }

    public function getDoctor()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }

    public function getDoctors()
    {
        return $this->hasOne(UserIdentity::ClassName(), ['id' => 'doctor_id']);
    }
}

controllers/ReceiveDoctorNoteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ReceiveDoctorNote;
use app\models\ReceiveDoctorNoteSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use app\models\PatientCard;
use app\models\MedicalCardForm;
/**
 * ReceiveDoctorNoteController implements the CRUD actions for ReceiveDoctorNote model.
 */
class ReceiveDoctorNoteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ReceiveDoctorNote models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (\Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId(Yii::$app->request->get('patient_id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
            $searchModel = new ReceiveDoctorNoteSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->renderPartial('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Displays a single ReceiveDoctorNote model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('viewPost') || (PatientCard::getUserIdByCardId($patient_id) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
            return $this->render('view', [
                'model' => $this->findModel($id),
                'patient' => PatientCard::findOne($patient_id),
                'medical_data' => MedicalCardForm::findOne($medical_card_id),
            ]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }   
    }

    /**
     * Creates a new ReceiveDoctorNote model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('createPost')) {
            $model = new ReceiveDoctorNote();

            $model->medical_card_form_id =  Yii::$app->request->get('medical_card_id');
            $model->datetime_added = date('Y-m-d H:i:s');

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id, 'medical_card_id' => $medical_card_id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'patient' => PatientCard::findOne($patient_id),
                    'medical_data' => MedicalCardForm::findOne($medical_card_id),
                ]);
            }
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Updates an existing ReceiveDoctorNote model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $patient_id, $medical_card_id)
    {
        if (\Yii::$app->user->can('updatePost')) {
            $model = $this->findModel($id);

            $model->medical_card_form_id =  Yii::$app->request->get('medical_card_id');

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id, 'patient_id' => $patient_id, 'medical_card_id' => $medical_card_id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'patient' => PatientCard::findOne($patient_id),
                    'medical_data' => MedicalCardForm::findOne($medical_card_id),
                ]);
            }
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Deletes an existing Surgeries model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id,$patient_id,$medical_card_id)
    {
        if (\Yii::$app->user->can('deletePost')) {
            $this->findModel($id)->delete();

            return $this->redirect(['medical-card-form/view', 'id' => $medical_card_id, 'patient_id' => $patient_id]);
        } else {
            throw new HttpException(403 ,'Forbidden');
        }
    }

    /**
     * Finds the ReceiveDoctorNote model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ReceiveDoctorNote the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ReceiveDoctorNote::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/receive-doctor-note/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Lang;
use yii\helpers\ArrayHelper;
use app\models\UserIdentity;

/* @var $this yii\web\View */
/* @var $model app\models\ReceiveDoctorNote */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="receive-doctor-note-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'complaints')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'disease_anamnesis')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'life_anamnesis')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'patient_objective_condition')->textarea(['rows' => 6]) ?>
    
    <?= $form->field($model, 'doctor_id')->dropDownList(ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),['class' => 'form-control', 'prompt' => Yii::t('patient_medical_form', 'Select doctor')]); 
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('yii', 'Create') : Yii::t('yii', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/receive-doctor-note/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReceiveDoctorNoteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="receive-doctor-note-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'medical_card_form_id') ?>

    <?= $form->field($model, 'complaints') ?>

    <?= $form->field($model, 'disease_anamnesis') ?>

    <?= $form->field($model, 'life_anamnesis') ?>

    <?php // echo $form->field($model, 'patient_objective_condition') ?>

    <?php // echo $form->field($model, 'datetime_added') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('receive_doctor_note', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('receive_doctor_note', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/receive-doctor-note/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ReceiveDoctorNote */

$this->title = Yii::t('receive_doctor_note', 'Create Receive Doctor Note');
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="receive-doctor-note-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/receive-doctor-note/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\UserIdentity;
use yii\widgets\Pjax;
use dosamigos\datetimepicker\DateTimePicker;
use app\models\Lang;
use app\models\MedicalCardForm;
use app\models\PatientCard;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ReceiveDoctorNoteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('receive_doctor_note', 'Receive Doctor Notes');
?>
<div class="receive-doctor-note-index">

    <p>
        <?php 
            if (\Yii::$app->user->can('createPost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) {
             echo Html::a(Yii::t('receive_doctor_note', 'Create Receive Doctor Note'), ['create', 'medical_card_id' => Yii::$app->request->get('id'), 'patient_id' => Yii::$app->request->get('patient_id')], ['class' => 'btn btn-success']);
            }
        ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'datetime_added',
                'value'     => 'datetime_added',
                'format' => 'raw',
                'options' => ['class'=>'several-datepicker-filters'],
                'filter' => DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'datetime_from',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd H:i:s',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'From'), 'class' => 'form-control datepicker-filter'],
                ]) . ' ' . DateTimePicker::widget([
                    'model'=> $searchModel,
                    'attribute'=>'datetime_to',
                    'language' => (Lang::getCurrent()->url == 'ua')? 'en' : Lang::getCurrent()->url,
                    'clientOptions' => [
                        'yearRange' => '1991:2099',
                        'format' => 'yyyy-mm-dd H:i:s',
                        'todayBtn' => true
                    ],
                    'options' => ['placeholder' => Yii::t('patient_card', 'To'), 'class' => 'form-control datepicker-filter'],
                ]) ,

            ],
            [
                'attribute' => 'doctor_full_name',
                'label' => Yii::t('patient_card', 'Doctor Full Name'),
                'value' => function ($model) {
                    if($model->user){
                        return $model->user->getFullName();
                    } else {
                        return NULL;
                    }
                },
                'filter' =>Html::activeDropDownList(
                    $searchModel, 
                    'user.id',
                    ArrayHelper::map(UserIdentity::getDoctors(), 'id', 'fullName'),
                    ['class' => 'form-control', 'prompt' => Yii::t('patient_medical_form', 'Select doctor')]
                ),
            ],

            [
               'class' => \yii\grid\ActionColumn::className(),
               'buttons'=>[
                    'view'=>function ($url, $model) {
                        if((\Yii::$app->user->can('viewPost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) || (PatientCard::getUserIdByCardId(Yii::$app->request->get('patient_id')) == Yii::$app->user->identity->id && Yii::$app->user->can('viewPatientProfile'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['receive-doctor-note/view','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-eye-open"></span>', $customurl, ['title' => Yii::t('yii', 'View'), 'data-pjax' => '0']);
                        }
                    },
                    'update' => function ($url, $model) {
                        if(\Yii::$app->user->can('updatePost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['receive-doctor-note/update','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-pencil"></span>', $customurl, ['title' => Yii::t('yii', 'Update'), 'data-pjax' => '0']);
                        }
                    },
                    'delete' => function ($url, $model) {
                        if(\Yii::$app->user->can('deletePost') && MedicalCardForm::getCardClosedTimeById(Yii::$app->request->get('id'))) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['receive-doctor-note/delete','id'=>$model['id'] , 'patient_id' => Yii::$app->request->get('patient_id'), 'medical_card_id' => Yii::$app->request->get('id')]); //$model->id для AR
                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-trash"></span>', $customurl, ['title' => Yii::t('yii', 'Delete'), 'data-pjax' => '0', 'data-method'=>'post']);
                        }
                    },
                ],
               'template'=>'{view} {update} {delete}',
           ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/receive-doctor-note/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ReceiveDoctorNote */

$this->title = Yii::t('receive_doctor_note', 'Update Receive Doctor Note:') ;
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_card', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title ;
?>
<div class="receive-doctor-note-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/receive-doctor-note/view.php
<?php


use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\UserIdentity;
/* @var $this yii\web\View */
/* @var $model app\models\ReceiveDoctorNote */

$this->title = Yii::t('receive_doctor_note', 'Receive Doctor Note');
if(Yii::$app->user->can('viewPost')) {
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Patient Cards'), 'url' => ['patient-card/index']];
}
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', $patient->first_name . ' ' . $patient->last_name . ' ' . $patient->middle_name), 'url' => ['patient-card/view', 'id'=>Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = ['label' => Yii::t('patient_medical_form', 'Medical card №') . $medical_data->medical_card_number, 'url' => ['medical-card-form/view', 'id'=>Yii::$app->request->get('medical_card_id'), 'patient_id' => Yii::$app->request->get('patient_id')]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="receive-doctor-note-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'complaints:ntext',
            'disease_anamnesis:ntext',
            'life_anamnesis:ntext',
            'patient_objective_condition:ntext',
            [
                'label' => Yii::t('receive_doctor_note','Responsible Doctor'),
                'value' => UserIdentity::getDoctorById($model->doctor_id),
            ],
        ],
    ]) ?>

</div>